name: Spell checking
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
  workflow_dispatch:

  
jobs:
  build:
    name: Spell checking
    # This job runs on Linux
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/jacarte/latex-build:latest27
      credentials:
        username: jacarte
        password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Build document
        run: |
          apt-get update
          apt-get install -y curl

          # Remove widows from the document
          WIDOW=$(cat ./.github/widow.tex)
          # escape WIDOW
          WIDOW=$(echo $WIDOW | sed 's/\//\\\//g')
          sed -i "s/%%FOR_WIDOW%%/\\\\input{.github\/widow.tex}/"  main.tex > fix.tex
          echo "Compiling without widows"
          cat fix.tex

          pdflatex -interaction=nonstopmode -shell-escape fix.tex || true
          sleep 30
          bibtex fix.aux || true
          sleep 30
          pdflatex -shell-escape -interaction=nonstopmode fix.tex || true
          sleep 15
          pdflatex -shell-escape -interaction=nonstopmode fix.tex || true
          sleep 15
        env:
          ADDCONTRIB: "False"  
          # Avoid widows, this helps the OCR for preventing the "CASING" error
          NOWIDOW: "True"
      
      - name: Upload assets to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fix.pdf 
          path: fix.pdf 

      - name: Save compilation sources
        run: |
          mkdir -p /sources
          cp -r ./ /sources
          cd /sources
          rm -rf .github
          rm -rf *.pdf
          rm fix.tex

      - name: Upload sources to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sources
          path: /sources 
  

      - name: Spell checking report
        run: |
          mkdir -p ./.github/rois
          pip3 install readability
          python3 ./.github/spell_check.py fix.pdf dico.text
        
      - name: GIT
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"


      - name: Annotate new pdf on a new branch
        run: |
          git config --global --add safe.directory /__w/main/main
          ls -R .
          
          cp -r ./.github/rois ./rois
          cp ./.github/report.json ./report.json

          python3 ./.github/create_html_report.py report.json index.html


          git rm -rf . && git checkout -b gh-pages
          git add rois index.html report.json && git commit -m 'Spell check report' 
          git push origin gh-pages --force
        env:
          REPO_KEY: '${{ secrets.REPO_KEY2 }}'
